### ISSUE TITLE
Error when calling localhost:9000/admin-home or 'domain':9000/admin-home

### ISSUE THREAD

**Issue by NN01010101** [jbuffin/WebsiteBuilder#1]
WebsiteBuilder-master/app/controllers/Application.scala at line 20:

17	def adminHome = IsAuthenticated { username => implicit request =>
18		Logger.debug("[Application.adminHome]")
19		if(username != "") {
20			Ok(views.html.admin(Site.getSiteByHostName(request.domain).get.siteName))
21		} else {
22			Redirect(routes.LoginController.login)
23		}
24	}

**Comment by jbuffin** [comment]
can you post the exact error you receive? A screenshot of the browser window would be best. I will look into the issue.

**Comment by NN01010101** [comment]
![screenshot 2015-02-18 08 40 49](https://cloud.githubusercontent.com/assets/10622794/6243816/feac1fa8-b749-11e4-8e58-2bedeabd8304.png)

**Comment by jbuffin** [comment]
You should be able to fix this by adding the hostname in the `sites` table in the postgres database. This is an oversight for first run. If you are running the app for the first time, you don't have any sites and so when it tries to get the site. I also need to catch that exception better there. I'll have a fix for this but as a workaround, you can add the site manually in the database.

**Comment by NN01010101** [comment]
Thanks!

**Comment by jbuffin** [comment]
https://github.com/jbuffin/WebsiteBuilder/pull/2

**Comment by jbuffin** [comment]
Check out the latest `master` and the issue should be fixed.
